### PR TITLE
Validate mixins

### LINKED ISSUE #179: Validate mixins during `create-builder` and `build`
### Adds buildpack mixins to builder layers label

**Given** I have a `buildpack.toml` with the following section:
```
[[stacks]]
  id = "some.stack.id"
  mixins = ["mixinA", "mixinB"]
```
**When** I run `pack create-builder` against the buildpack and stack `some.stack.id`
**Then** The builder contains the buildpack mixins in its `io.buildpacks.buildpack.layers` label:
```
{
  "some.buildpack.id": {
    "some.buildpack.version": {
      "stacks": [{
        "id": "some.stack.id",
        "mixins": ["mixinA", "mixinB"]
      }],
      ...
    }
  },
  ...
}
```

> **NOTE**: Order buildpacks will not have mixins (as they have no stacks), so they can be skipped over

----

#### Mixins satisfied
**Given** I have a build image with a `io.buildpacks.stack.mixins` label: 
```
[ "mixinA", "build:mixinB", "mixinC" ]
```
**And** I have a buildpack that requires mixins: `mixinA`, `build:mixinB`, `run:mixinD`
**When** I run `pack create-builder` against the build image and buildpack
**Then** the command succeeds

> **NOTE**: `run:`-prefixed mixins do not need to be validated during `create-builder` (e.g. `run:mixinD` above).

----

#### Mixins unsatisfied
**Given** I have a build image `some/build` with a `io.buildpacks.stack.mixins` label: 
```
[ "mixinA", "build:mixinB", "mixinC" ]
```
**And** I have a buildpack that requires mixins: `mixinX`, `mixinY`, `build:mixinB`, `run:mixinD`
**When** I run `pack create-builder` against the build image and buildpack
**Then** the command fails with error similar to:
```
Error: invalid build image 'some/build': buildpack 'some.buildpack.id@some.buildpack.version' requires missing mixin(s): mixinX, mixinY
```

> **NOTE**: `run:`-prefixed mixins do not need to be validated during `create-builder` (e.g. `run:mixinD` above).

#### Mixins match
**Given** I have a builder image with a `io.buildpacks.stack.mixins` label:
```
["mixinA", "build:mixinB"]
```
**And** the builder's corresponding run image has a `io.buildpacks.stack.mixins` label:
```
["mixinA", "run:mixinC"]
```
**When** I run `pack build` against the builder
**Then** the command succeeds

----

#### Missing one or more common mixins
**Given** I have a builder image with a `io.buildpacks.stack.mixins` label:
```
[ ]
```
**And** the builder's corresponding run image has a `io.buildpacks.stack.mixins` label:
```
["mixinA", "mixinB"]
```
**When** I run `pack build` against the builder
**Then** the command fails with error similar to:
```
Error: invalid builder image: 'some/builder' requires missing mixin(s): mixinA, mixinB
``` 

> **NOTE**: Similar behavior expected for common mixin missing from run image

----

#### Invalid mixin
**Given** I have a builder image with a `io.buildpacks.stack.mixins` label:
```
[ "run:mixinA", "run:mixinB" ]
```
**When** I run `pack build` against the builder
**Then** the command fails with error similar to:
```
Error: invalid builder image: 'some/builder' contains run-only mixin(s): run:mixinA, run:mixinB
```

> **NOTE**: Similar behavior expected for build-only mixin present in run image

----

#### Mixins satisfied
**Given** I have a builder image with a `io.buildpacks.stack.mixins` label: 
```
[ "mixinA", "build:mixinB", "mixinC" ]
```
**And** the builder's corresponding run image has a `io.buildpacks.stack.mixins` label: 
```
[ "mixinA", "mixinC", "run:mixinD" ]
```
**And** I have a buildpack that requires mixins: `mixinA`, `build:mixinB`, `run:mixinD`
**When** I run `pack build` against the builder image and buildpack
**Then** the command succeeds

> **NOTE**:
> - both `build:`-prefixed and `run:`-prefixed must be satisfied
> - must behave similarly with `--buildpack` and/or `--run-image` flags

----

#### Mixins unsatisfied
**Given** I have a builder image `some/builder` with a `io.buildpacks.stack.mixins` label: 
```
[ "mixinA", "build:mixinB" ]
```
**And** the builder's corresponding run image `some/run` has a `io.buildpacks.stack.mixins` label: 
```
[ "mixinA" ]
```
**And** I have a buildpack that requires mixins: `mixinA`, `build:mixinB`, `mixinC`, `run:mixinD`
**When** I run `pack build` against the builder image and buildpack
**Then** the command fails with error similar to:
```
Error: invalid stack image(s): buildpack 'some.buildpack.id@some.buildpack.version' requires missing mixin(s): mixinC, run:mixinD
```

> **NOTE**:
> - both `build:`-prefixed and `run:`-prefixed must be satisfied
> - must behave similarly with `--buildpack` and/or `--run-image` flags

### PR DESCRIPTION
**Pull request by ameyer-pivotal**
- During `create-builder`, check that buildpack mixins are satisfied
- During `build`, check that stack image mixins are in agreement, and that buildpack mixins are satisfied

Signed-off-by: Andrew Meyer <ameyer@pivotal.io>

Resolves #179

### CODE REVIEW

File: build_test.go [hunk 1]
```diff
@@ -1016,6 +1050,39 @@ func testBuild(t *testing.T, when spec.G, it spec.S) {
...
+					h.AssertNil(t, defaultBuilderImage.SetLabel("io.buildpacks.stack.mixins", `["mixinA"]`))
+					h.AssertNil(t, fakeDefaultRunImage.SetLabel("io.buildpacks.stack.mixins", `["mixinA"]`))
+				})
+				it("returns an error", func() {
+					err := subject.Build(context.TODO(), BuildOptions{
+						Image:   "some/app",
+						Builder: builderName,
+					})
+
+					h.AssertError(t, err, "validating stack mixins: buildpack 'buildpack.id@buildpack.version' requires missing mixin(s): build:mixinY, mixinX, run:mixinZ")
```
Comment (simonjjones) [inline build_test.go]: This appears to be testing the buildpack mixins rather than having differing mixins between the builder & run images, as appears to be desired by the context message.

Comment (ameyer-pivotal) [reply build_test.go]: Good catch! I must have been on autopilot. Will fix.

File: builder/builder.go [hunk 2]
```diff
@@ -61,8 +63,8 @@ type orderTOML struct {
 	Order dist.Order `toml:"order"`
 }
 
-// GetBuilder constructs builder from builder image
-func GetBuilder(img imgutil.Image) (*Builder, error) {
+// Get constructs a builder from a builder image
+func Get(img imgutil.Image) (*Builder, error) {
```
Comment (simonjjones) [inline builder/builder.go]: These naming refactors seem super helpful, and generally I am in favor of them. I do wonder, however, whether they make sense as part of this PR, or if they should be added through a separate one, given they don't directly contribute to validating our mixins

File: dist/image.go [hunk 3]
```diff
@@ -9,6 +9,10 @@ import (
 	"github.com/buildpack/pack/style"
 )
 
+const (
+	MixinsLabel = "io.buildpacks.stack.mixins"
+)
```
Comment (simonjjones) [inline dist/image.go]: This constant doesn't feel like it belongs here alongside these generic label getter & setters. Everywhere else `Get` or `Set` `Label` is consumed the label name is sourced from somewhere else.

File: build_test.go (hunk 1 above)
Comment (ameyer-pivotal) [reply build_test.go]: Done.

File: dist/image.go (hunk 3 above)
Comment (ameyer-pivotal) [reply dist/image.go]: Done.

File: builder/builder.go (hunk 2 above)
Comment (ameyer-pivotal) [reply builder/builder.go]: Will definitely keep in mind for next PR
